// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by SoftDreams Developer
// **************************************************************************
// ignore_for_file: constant_identifier_names, non_constant_identifier_names

/// {@template assets_generator.ASSETS_ICONS_EMPTY_FOLDER_PNG.preview}
/// ![](c:\projectsoftdreams\demo_fresher_getx\assets/icons/empty-folder.png)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_ICONS_EMPTY_EMPTY_FOLDER_PNG.preview}
/// ![](c:\projectsoftdreams\demo_fresher_getx\assets/icons/empty/empty-folder.png)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_ICONS_IC_APP_SVG.preview}
/// ![](c:\projectsoftdreams\demo_fresher_getx\assets/icons/ic_app.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_ICONS_IC_ASSIGN_TASKS_SVG.preview}
/// ![](c:\projectsoftdreams\demo_fresher_getx\assets/icons/ic_assign_tasks.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_ICONS_IC_COMMENT_SVG.preview}
/// ![](c:\projectsoftdreams\demo_fresher_getx\assets/icons/ic_comment.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_ICONS_IC_COMMENT_REMINDER_SVG.preview}
/// ![](c:\projectsoftdreams\demo_fresher_getx\assets/icons/ic_comment_reminder.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_ICONS_IC_EXPAND_LESS_SVG.preview}
/// ![](c:\projectsoftdreams\demo_fresher_getx\assets/icons/ic_expand_less.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_ICONS_IC_FAILURE_SVG.preview}
/// ![](c:\projectsoftdreams\demo_fresher_getx\assets/icons/ic_failure.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_ICONS_IC_FINGERPRINT_SVG.preview}
/// ![](c:\projectsoftdreams\demo_fresher_getx\assets/icons/ic_fingerprint.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_ICONS_IC_FOLDER_SELECTED_SVG.preview}
/// ![](c:\projectsoftdreams\demo_fresher_getx\assets/icons/ic_folder_selected.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_ICONS_IC_FOLDER_UN_SELECTED_SVG.preview}
/// ![](c:\projectsoftdreams\demo_fresher_getx\assets/icons/ic_folder_un_selected.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_ICONS_IC_MENU_ACTIVE_SVG.preview}
/// ![](c:\projectsoftdreams\demo_fresher_getx\assets/icons/ic_menu_active.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_ICONS_IC_MENU_NON_ACTIVE_SVG.preview}
/// ![](c:\projectsoftdreams\demo_fresher_getx\assets/icons/ic_menu_non_active.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_ICONS_IC_NOTE_SVG.preview}
/// ![](c:\projectsoftdreams\demo_fresher_getx\assets/icons/ic_note.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_ICONS_IC_NOTIFICATION_ACTIVE_SVG.preview}
/// ![](c:\projectsoftdreams\demo_fresher_getx\assets/icons/ic_notification_active.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_ICONS_IC_NOTIFICATION_NON_ACTIVE_SVG.preview}
/// ![](c:\projectsoftdreams\demo_fresher_getx\assets/icons/ic_notification_non_active.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_ICONS_IC_OVERVIEW_ACTIVE_SVG.preview}
/// ![](c:\projectsoftdreams\demo_fresher_getx\assets/icons/ic_overview_active.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_ICONS_IC_OVERVIEW_NON_ACTIVE_SVG.preview}
/// ![](c:\projectsoftdreams\demo_fresher_getx\assets/icons/ic_overview_non_active.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_ICONS_IC_PASSWORD_SVG.preview}
/// ![](c:\projectsoftdreams\demo_fresher_getx\assets/icons/ic_password.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_ICONS_IC_PEOPLE_SVG.preview}
/// ![](c:\projectsoftdreams\demo_fresher_getx\assets/icons/ic_people.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_ICONS_IC_PERSON_SVG.preview}
/// ![](c:\projectsoftdreams\demo_fresher_getx\assets/icons/ic_person.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_ICONS_IC_PROGRESS_SVG.preview}
/// ![](c:\projectsoftdreams\demo_fresher_getx\assets/icons/ic_progress.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_ICONS_IC_PROJECT_ACTIVE_SVG.preview}
/// ![](c:\projectsoftdreams\demo_fresher_getx\assets/icons/ic_project_active.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_ICONS_IC_PROJECT_NON_ACTIVE_SVG.preview}
/// ![](c:\projectsoftdreams\demo_fresher_getx\assets/icons/ic_project_non_active.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_ICONS_IC_REMINDER_SVG.preview}
/// ![](c:\projectsoftdreams\demo_fresher_getx\assets/icons/ic_reminder.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_ICONS_IC_SNACK_BAR_FAILURE_SVG.preview}
/// ![](c:\projectsoftdreams\demo_fresher_getx\assets/icons/ic_snack_bar_failure.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_ICONS_IC_SNACK_BAR_SUCCESS_SVG.preview}
/// ![](c:\projectsoftdreams\demo_fresher_getx\assets/icons/ic_snack_bar_success.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_ICONS_IC_STATUS_SVG.preview}
/// ![](c:\projectsoftdreams\demo_fresher_getx\assets/icons/ic_status.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_ICONS_IC_SUCCESS_SVG.preview}
/// ![](c:\projectsoftdreams\demo_fresher_getx\assets/icons/ic_success.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_ICONS_IC_TASK_ACTIVE_SVG.preview}
/// ![](c:\projectsoftdreams\demo_fresher_getx\assets/icons/ic_task_active.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_ICONS_IC_TASK_NON_ACTIVE_SVG.preview}
/// ![](c:\projectsoftdreams\demo_fresher_getx\assets/icons/ic_task_non_active.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_ICONS_IC_TAX_SVG.preview}
/// ![](c:\projectsoftdreams\demo_fresher_getx\assets/icons/ic_tax.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_ICONS_IC_USER_SELECTED_SVG.preview}
/// ![](c:\projectsoftdreams\demo_fresher_getx\assets/icons/ic_user_selected.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_ICONS_IC_USER_UN_SELECTED_SVG.preview}
/// ![](c:\projectsoftdreams\demo_fresher_getx\assets/icons/ic_user_un_selected.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_ICONS_IC_WARNING_SVG.preview}
/// ![](c:\projectsoftdreams\demo_fresher_getx\assets/icons/ic_warning.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_ICONS_ICON_ALARM_CLOCK_SVG.preview}
/// ![](c:\projectsoftdreams\demo_fresher_getx\assets/icons/icon_alarm_clock.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_ICONS_ICON_APPEAR_EYE_SVG.preview}
/// ![](c:\projectsoftdreams\demo_fresher_getx\assets/icons/icon_appear_eye.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_ICONS_ICON_ATTACH_FILE_SVG.preview}
/// ![](c:\projectsoftdreams\demo_fresher_getx\assets/icons/icon_attach_file.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_ICONS_ICON_CAMERA_SVG.preview}
/// ![](c:\projectsoftdreams\demo_fresher_getx\assets/icons/icon_camera.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_ICONS_ICON_EDIT_SVG.preview}
/// ![](c:\projectsoftdreams\demo_fresher_getx\assets/icons/icon_edit.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_ICONS_ICON_HIDDEN_EYE_SVG.preview}
/// ![](c:\projectsoftdreams\demo_fresher_getx\assets/icons/icon_hidden_eye.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_ICONS_ICON_IMAGE_CAPTURE_SVG.preview}
/// ![](c:\projectsoftdreams\demo_fresher_getx\assets/icons/icon_image_Capture.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_ICONS_ICON_LANGUAGE_EN_PNG.preview}
/// ![](c:\projectsoftdreams\demo_fresher_getx\assets/icons/icon_language_en.png)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_ICONS_ICON_LANGUAGE_VN_PNG.preview}
/// ![](c:\projectsoftdreams\demo_fresher_getx\assets/icons/icon_language_vn.png)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_ICONS_ICON_LIST_SVG.preview}
/// ![](c:\projectsoftdreams\demo_fresher_getx\assets/icons/icon_list.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_ICONS_ICON_REFRESH_SVG.preview}
/// ![](c:\projectsoftdreams\demo_fresher_getx\assets/icons/icon_refresh.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_ICONS_ICON_REMOVE_SVG.preview}
/// ![](c:\projectsoftdreams\demo_fresher_getx\assets/icons/icon_remove.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_ICONS_ICON_SEND_SVG.preview}
/// ![](c:\projectsoftdreams\demo_fresher_getx\assets/icons/icon_send.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_ICONS_ICON_SNACK_BAR_NOTIFICATION_SVG.preview}
/// ![](c:\projectsoftdreams\demo_fresher_getx\assets/icons/icon_snack_bar_notification.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_ICONS_ICON_SNACK_BAR_WARNING_SVG.preview}
/// ![](c:\projectsoftdreams\demo_fresher_getx\assets/icons/icon_snack_bar_warning.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_ICONS_IMAGES_BOTLEFT1_PNG.preview}
/// ![](c:\projectsoftdreams\demo_fresher_getx\assets/icons/images_botLeft1.png)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_ICONS_IMAGES_BOTRIGHT1_PNG.preview}
/// ![](c:\projectsoftdreams\demo_fresher_getx\assets/icons/images_botRight1.png)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_ICONS_IMAGES_TOPLEFT1_PNG.preview}
/// ![](c:\projectsoftdreams\demo_fresher_getx\assets/icons/images_topLeft1.png)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_ICONS_IMAGES_TOPRIGHT1_PNG.preview}
/// ![](c:\projectsoftdreams\demo_fresher_getx\assets/icons/images_topRight1.png)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_ICONS_IMG_STOP_QR_PNG.preview}
/// ![](c:\projectsoftdreams\demo_fresher_getx\assets/icons/img_stop_qr.png)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_ICONS_LOGIN_USER_ICON_SVG.preview}
/// ![](c:\projectsoftdreams\demo_fresher_getx\assets/icons/login_user_icon.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_ICONS_SEARCH_ICON_SVG.preview}
/// ![](c:\projectsoftdreams\demo_fresher_getx\assets/icons/search_icon.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_ICONS_THREE_DOT_ICON_SVG.preview}
/// ![](c:\projectsoftdreams\demo_fresher_getx\assets/icons/three_dot_icon.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_ICONS_UPDATE_PROGRESS_ICON_SVG.preview}
/// ![](c:\projectsoftdreams\demo_fresher_getx\assets/icons/update_progress_icon.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_IMG_APP_PNG.preview}
/// ![](c:\projectsoftdreams\demo_fresher_getx\assets/images/img_app.png)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_IMG_BANNER_PNG.preview}
/// ![](c:\projectsoftdreams\demo_fresher_getx\assets/images/img_banner.png)
/// {@endtemplate}

// ignore_for_file: camel_case_types, unused_element
class _ {}