// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by SoftDreams Developer
// **************************************************************************
// ignore_for_file: constant_identifier_names, non_constant_identifier_names

class Assets {
  const Assets._();
  static const String package = 'demo_fresher_getx';

  static bool isFromModules = false;

  /// {@macro assets_generator.ASSETS_ICONS_EMPTY_FOLDER_PNG.preview}
  static String get ASSETS_ICONS_EMPTY_FOLDER_PNG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/empty-folder.png';

  /// {@macro assets_generator.ASSETS_ICONS_EMPTY_EMPTY_FOLDER_PNG.preview}
  static String get ASSETS_ICONS_EMPTY_EMPTY_FOLDER_PNG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/empty/empty-folder.png';

  /// {@macro assets_generator.ASSETS_ICONS_IC_APP_SVG.preview}
  static String get ASSETS_ICONS_IC_APP_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/ic_app.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_ASSIGN_TASKS_SVG.preview}
  static String get ASSETS_ICONS_IC_ASSIGN_TASKS_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/ic_assign_tasks.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_COMMENT_SVG.preview}
  static String get ASSETS_ICONS_IC_COMMENT_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/ic_comment.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_COMMENT_REMINDER_SVG.preview}
  static String get ASSETS_ICONS_IC_COMMENT_REMINDER_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/ic_comment_reminder.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_EXPAND_LESS_SVG.preview}
  static String get ASSETS_ICONS_IC_EXPAND_LESS_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/ic_expand_less.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_FAILURE_SVG.preview}
  static String get ASSETS_ICONS_IC_FAILURE_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/ic_failure.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_FINGERPRINT_SVG.preview}
  static String get ASSETS_ICONS_IC_FINGERPRINT_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/ic_fingerprint.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_FOLDER_SELECTED_SVG.preview}
  static String get ASSETS_ICONS_IC_FOLDER_SELECTED_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/ic_folder_selected.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_FOLDER_UN_SELECTED_SVG.preview}
  static String get ASSETS_ICONS_IC_FOLDER_UN_SELECTED_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/ic_folder_un_selected.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_MENU_ACTIVE_SVG.preview}
  static String get ASSETS_ICONS_IC_MENU_ACTIVE_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/ic_menu_active.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_MENU_NON_ACTIVE_SVG.preview}
  static String get ASSETS_ICONS_IC_MENU_NON_ACTIVE_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/ic_menu_non_active.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_NOTE_SVG.preview}
  static String get ASSETS_ICONS_IC_NOTE_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/ic_note.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_NOTIFICATION_ACTIVE_SVG.preview}
  static String get ASSETS_ICONS_IC_NOTIFICATION_ACTIVE_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/ic_notification_active.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_NOTIFICATION_NON_ACTIVE_SVG.preview}
  static String get ASSETS_ICONS_IC_NOTIFICATION_NON_ACTIVE_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/ic_notification_non_active.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_OVERVIEW_ACTIVE_SVG.preview}
  static String get ASSETS_ICONS_IC_OVERVIEW_ACTIVE_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/ic_overview_active.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_OVERVIEW_NON_ACTIVE_SVG.preview}
  static String get ASSETS_ICONS_IC_OVERVIEW_NON_ACTIVE_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/ic_overview_non_active.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_PASSWORD_SVG.preview}
  static String get ASSETS_ICONS_IC_PASSWORD_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/ic_password.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_PEOPLE_SVG.preview}
  static String get ASSETS_ICONS_IC_PEOPLE_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/ic_people.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_PERSON_SVG.preview}
  static String get ASSETS_ICONS_IC_PERSON_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/ic_person.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_PROGRESS_SVG.preview}
  static String get ASSETS_ICONS_IC_PROGRESS_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/ic_progress.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_PROJECT_ACTIVE_SVG.preview}
  static String get ASSETS_ICONS_IC_PROJECT_ACTIVE_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/ic_project_active.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_PROJECT_NON_ACTIVE_SVG.preview}
  static String get ASSETS_ICONS_IC_PROJECT_NON_ACTIVE_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/ic_project_non_active.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_REMINDER_SVG.preview}
  static String get ASSETS_ICONS_IC_REMINDER_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/ic_reminder.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_SNACK_BAR_FAILURE_SVG.preview}
  static String get ASSETS_ICONS_IC_SNACK_BAR_FAILURE_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/ic_snack_bar_failure.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_SNACK_BAR_SUCCESS_SVG.preview}
  static String get ASSETS_ICONS_IC_SNACK_BAR_SUCCESS_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/ic_snack_bar_success.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_STATUS_SVG.preview}
  static String get ASSETS_ICONS_IC_STATUS_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/ic_status.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_SUCCESS_SVG.preview}
  static String get ASSETS_ICONS_IC_SUCCESS_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/ic_success.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_TASK_ACTIVE_SVG.preview}
  static String get ASSETS_ICONS_IC_TASK_ACTIVE_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/ic_task_active.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_TASK_NON_ACTIVE_SVG.preview}
  static String get ASSETS_ICONS_IC_TASK_NON_ACTIVE_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/ic_task_non_active.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_TAX_SVG.preview}
  static String get ASSETS_ICONS_IC_TAX_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/ic_tax.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_USER_SELECTED_SVG.preview}
  static String get ASSETS_ICONS_IC_USER_SELECTED_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/ic_user_selected.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_USER_UN_SELECTED_SVG.preview}
  static String get ASSETS_ICONS_IC_USER_UN_SELECTED_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/ic_user_un_selected.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_WARNING_SVG.preview}
  static String get ASSETS_ICONS_IC_WARNING_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/ic_warning.svg';

  /// {@macro assets_generator.ASSETS_ICONS_ICON_ALARM_CLOCK_SVG.preview}
  static String get ASSETS_ICONS_ICON_ALARM_CLOCK_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/icon_alarm_clock.svg';

  /// {@macro assets_generator.ASSETS_ICONS_ICON_APPEAR_EYE_SVG.preview}
  static String get ASSETS_ICONS_ICON_APPEAR_EYE_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/icon_appear_eye.svg';

  /// {@macro assets_generator.ASSETS_ICONS_ICON_ATTACH_FILE_SVG.preview}
  static String get ASSETS_ICONS_ICON_ATTACH_FILE_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/icon_attach_file.svg';

  /// {@macro assets_generator.ASSETS_ICONS_ICON_CAMERA_SVG.preview}
  static String get ASSETS_ICONS_ICON_CAMERA_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/icon_camera.svg';

  /// {@macro assets_generator.ASSETS_ICONS_ICON_EDIT_SVG.preview}
  static String get ASSETS_ICONS_ICON_EDIT_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/icon_edit.svg';

  /// {@macro assets_generator.ASSETS_ICONS_ICON_HIDDEN_EYE_SVG.preview}
  static String get ASSETS_ICONS_ICON_HIDDEN_EYE_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/icon_hidden_eye.svg';

  /// {@macro assets_generator.ASSETS_ICONS_ICON_IMAGE_CAPTURE_SVG.preview}
  static String get ASSETS_ICONS_ICON_IMAGE_CAPTURE_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/icon_image_Capture.svg';

  /// {@macro assets_generator.ASSETS_ICONS_ICON_LANGUAGE_EN_PNG.preview}
  static String get ASSETS_ICONS_ICON_LANGUAGE_EN_PNG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/icon_language_en.png';

  /// {@macro assets_generator.ASSETS_ICONS_ICON_LANGUAGE_VN_PNG.preview}
  static String get ASSETS_ICONS_ICON_LANGUAGE_VN_PNG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/icon_language_vn.png';

  /// {@macro assets_generator.ASSETS_ICONS_ICON_LIST_SVG.preview}
  static String get ASSETS_ICONS_ICON_LIST_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/icon_list.svg';

  /// {@macro assets_generator.ASSETS_ICONS_ICON_REFRESH_SVG.preview}
  static String get ASSETS_ICONS_ICON_REFRESH_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/icon_refresh.svg';

  /// {@macro assets_generator.ASSETS_ICONS_ICON_REMOVE_SVG.preview}
  static String get ASSETS_ICONS_ICON_REMOVE_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/icon_remove.svg';

  /// {@macro assets_generator.ASSETS_ICONS_ICON_SEND_SVG.preview}
  static String get ASSETS_ICONS_ICON_SEND_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/icon_send.svg';

  /// {@macro assets_generator.ASSETS_ICONS_ICON_SNACK_BAR_NOTIFICATION_SVG.preview}
  static String get ASSETS_ICONS_ICON_SNACK_BAR_NOTIFICATION_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/icon_snack_bar_notification.svg';

  /// {@macro assets_generator.ASSETS_ICONS_ICON_SNACK_BAR_WARNING_SVG.preview}
  static String get ASSETS_ICONS_ICON_SNACK_BAR_WARNING_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/icon_snack_bar_warning.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IMAGES_BOTLEFT1_PNG.preview}
  static String get ASSETS_ICONS_IMAGES_BOTLEFT1_PNG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/images_botLeft1.png';

  /// {@macro assets_generator.ASSETS_ICONS_IMAGES_BOTRIGHT1_PNG.preview}
  static String get ASSETS_ICONS_IMAGES_BOTRIGHT1_PNG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/images_botRight1.png';

  /// {@macro assets_generator.ASSETS_ICONS_IMAGES_TOPLEFT1_PNG.preview}
  static String get ASSETS_ICONS_IMAGES_TOPLEFT1_PNG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/images_topLeft1.png';

  /// {@macro assets_generator.ASSETS_ICONS_IMAGES_TOPRIGHT1_PNG.preview}
  static String get ASSETS_ICONS_IMAGES_TOPRIGHT1_PNG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/images_topRight1.png';

  /// {@macro assets_generator.ASSETS_ICONS_IMG_STOP_QR_PNG.preview}
  static String get ASSETS_ICONS_IMG_STOP_QR_PNG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/img_stop_qr.png';

  /// {@macro assets_generator.ASSETS_ICONS_LOGIN_USER_ICON_SVG.preview}
  static String get ASSETS_ICONS_LOGIN_USER_ICON_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/login_user_icon.svg';

  /// {@macro assets_generator.ASSETS_ICONS_SEARCH_ICON_SVG.preview}
  static String get ASSETS_ICONS_SEARCH_ICON_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/search_icon.svg';

  /// {@macro assets_generator.ASSETS_ICONS_THREE_DOT_ICON_SVG.preview}
  static String get ASSETS_ICONS_THREE_DOT_ICON_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/three_dot_icon.svg';

  /// {@macro assets_generator.ASSETS_ICONS_UPDATE_PROGRESS_ICON_SVG.preview}
  static String get ASSETS_ICONS_UPDATE_PROGRESS_ICON_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/icons/update_progress_icon.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_IMG_APP_PNG.preview}
  static String get ASSETS_IMAGES_IMG_APP_PNG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/img_app.png';

  /// {@macro assets_generator.ASSETS_IMAGES_IMG_BANNER_PNG.preview}
  static String get ASSETS_IMAGES_IMG_BANNER_PNG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/img_banner.png';

  static String get ASSETS_LOCALES_EN_US_JSON =>
      '${isFromModules ? "packages/$package/" : ""}assets/locales/en_US.json';

  static String get ASSETS_LOCALES_VI_VN_JSON =>
      '${isFromModules ? "packages/$package/" : ""}assets/locales/vi_VN.json';
}

final List<String> assetsArray = <String>[
  /// {@macro assets_generator.ASSETS_ICONS_EMPTY_FOLDER_PNG.preview}
  Assets.ASSETS_ICONS_EMPTY_FOLDER_PNG,

  /// {@macro assets_generator.ASSETS_ICONS_EMPTY_EMPTY_FOLDER_PNG.preview}
  Assets.ASSETS_ICONS_EMPTY_EMPTY_FOLDER_PNG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_APP_SVG.preview}
  Assets.ASSETS_ICONS_IC_APP_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_ASSIGN_TASKS_SVG.preview}
  Assets.ASSETS_ICONS_IC_ASSIGN_TASKS_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_COMMENT_SVG.preview}
  Assets.ASSETS_ICONS_IC_COMMENT_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_COMMENT_REMINDER_SVG.preview}
  Assets.ASSETS_ICONS_IC_COMMENT_REMINDER_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_EXPAND_LESS_SVG.preview}
  Assets.ASSETS_ICONS_IC_EXPAND_LESS_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_FAILURE_SVG.preview}
  Assets.ASSETS_ICONS_IC_FAILURE_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_FINGERPRINT_SVG.preview}
  Assets.ASSETS_ICONS_IC_FINGERPRINT_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_FOLDER_SELECTED_SVG.preview}
  Assets.ASSETS_ICONS_IC_FOLDER_SELECTED_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_FOLDER_UN_SELECTED_SVG.preview}
  Assets.ASSETS_ICONS_IC_FOLDER_UN_SELECTED_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_MENU_ACTIVE_SVG.preview}
  Assets.ASSETS_ICONS_IC_MENU_ACTIVE_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_MENU_NON_ACTIVE_SVG.preview}
  Assets.ASSETS_ICONS_IC_MENU_NON_ACTIVE_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_NOTE_SVG.preview}
  Assets.ASSETS_ICONS_IC_NOTE_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_NOTIFICATION_ACTIVE_SVG.preview}
  Assets.ASSETS_ICONS_IC_NOTIFICATION_ACTIVE_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_NOTIFICATION_NON_ACTIVE_SVG.preview}
  Assets.ASSETS_ICONS_IC_NOTIFICATION_NON_ACTIVE_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_OVERVIEW_ACTIVE_SVG.preview}
  Assets.ASSETS_ICONS_IC_OVERVIEW_ACTIVE_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_OVERVIEW_NON_ACTIVE_SVG.preview}
  Assets.ASSETS_ICONS_IC_OVERVIEW_NON_ACTIVE_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_PASSWORD_SVG.preview}
  Assets.ASSETS_ICONS_IC_PASSWORD_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_PEOPLE_SVG.preview}
  Assets.ASSETS_ICONS_IC_PEOPLE_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_PERSON_SVG.preview}
  Assets.ASSETS_ICONS_IC_PERSON_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_PROGRESS_SVG.preview}
  Assets.ASSETS_ICONS_IC_PROGRESS_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_PROJECT_ACTIVE_SVG.preview}
  Assets.ASSETS_ICONS_IC_PROJECT_ACTIVE_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_PROJECT_NON_ACTIVE_SVG.preview}
  Assets.ASSETS_ICONS_IC_PROJECT_NON_ACTIVE_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_REMINDER_SVG.preview}
  Assets.ASSETS_ICONS_IC_REMINDER_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_SNACK_BAR_FAILURE_SVG.preview}
  Assets.ASSETS_ICONS_IC_SNACK_BAR_FAILURE_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_SNACK_BAR_SUCCESS_SVG.preview}
  Assets.ASSETS_ICONS_IC_SNACK_BAR_SUCCESS_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_STATUS_SVG.preview}
  Assets.ASSETS_ICONS_IC_STATUS_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_SUCCESS_SVG.preview}
  Assets.ASSETS_ICONS_IC_SUCCESS_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_TASK_ACTIVE_SVG.preview}
  Assets.ASSETS_ICONS_IC_TASK_ACTIVE_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_TASK_NON_ACTIVE_SVG.preview}
  Assets.ASSETS_ICONS_IC_TASK_NON_ACTIVE_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_TAX_SVG.preview}
  Assets.ASSETS_ICONS_IC_TAX_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_USER_SELECTED_SVG.preview}
  Assets.ASSETS_ICONS_IC_USER_SELECTED_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_USER_UN_SELECTED_SVG.preview}
  Assets.ASSETS_ICONS_IC_USER_UN_SELECTED_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_WARNING_SVG.preview}
  Assets.ASSETS_ICONS_IC_WARNING_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_ICON_ALARM_CLOCK_SVG.preview}
  Assets.ASSETS_ICONS_ICON_ALARM_CLOCK_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_ICON_APPEAR_EYE_SVG.preview}
  Assets.ASSETS_ICONS_ICON_APPEAR_EYE_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_ICON_ATTACH_FILE_SVG.preview}
  Assets.ASSETS_ICONS_ICON_ATTACH_FILE_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_ICON_CAMERA_SVG.preview}
  Assets.ASSETS_ICONS_ICON_CAMERA_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_ICON_EDIT_SVG.preview}
  Assets.ASSETS_ICONS_ICON_EDIT_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_ICON_HIDDEN_EYE_SVG.preview}
  Assets.ASSETS_ICONS_ICON_HIDDEN_EYE_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_ICON_IMAGE_CAPTURE_SVG.preview}
  Assets.ASSETS_ICONS_ICON_IMAGE_CAPTURE_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_ICON_LANGUAGE_EN_PNG.preview}
  Assets.ASSETS_ICONS_ICON_LANGUAGE_EN_PNG,

  /// {@macro assets_generator.ASSETS_ICONS_ICON_LANGUAGE_VN_PNG.preview}
  Assets.ASSETS_ICONS_ICON_LANGUAGE_VN_PNG,

  /// {@macro assets_generator.ASSETS_ICONS_ICON_LIST_SVG.preview}
  Assets.ASSETS_ICONS_ICON_LIST_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_ICON_REFRESH_SVG.preview}
  Assets.ASSETS_ICONS_ICON_REFRESH_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_ICON_REMOVE_SVG.preview}
  Assets.ASSETS_ICONS_ICON_REMOVE_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_ICON_SEND_SVG.preview}
  Assets.ASSETS_ICONS_ICON_SEND_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_ICON_SNACK_BAR_NOTIFICATION_SVG.preview}
  Assets.ASSETS_ICONS_ICON_SNACK_BAR_NOTIFICATION_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_ICON_SNACK_BAR_WARNING_SVG.preview}
  Assets.ASSETS_ICONS_ICON_SNACK_BAR_WARNING_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IMAGES_BOTLEFT1_PNG.preview}
  Assets.ASSETS_ICONS_IMAGES_BOTLEFT1_PNG,

  /// {@macro assets_generator.ASSETS_ICONS_IMAGES_BOTRIGHT1_PNG.preview}
  Assets.ASSETS_ICONS_IMAGES_BOTRIGHT1_PNG,

  /// {@macro assets_generator.ASSETS_ICONS_IMAGES_TOPLEFT1_PNG.preview}
  Assets.ASSETS_ICONS_IMAGES_TOPLEFT1_PNG,

  /// {@macro assets_generator.ASSETS_ICONS_IMAGES_TOPRIGHT1_PNG.preview}
  Assets.ASSETS_ICONS_IMAGES_TOPRIGHT1_PNG,

  /// {@macro assets_generator.ASSETS_ICONS_IMG_STOP_QR_PNG.preview}
  Assets.ASSETS_ICONS_IMG_STOP_QR_PNG,

  /// {@macro assets_generator.ASSETS_ICONS_LOGIN_USER_ICON_SVG.preview}
  Assets.ASSETS_ICONS_LOGIN_USER_ICON_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_SEARCH_ICON_SVG.preview}
  Assets.ASSETS_ICONS_SEARCH_ICON_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_THREE_DOT_ICON_SVG.preview}
  Assets.ASSETS_ICONS_THREE_DOT_ICON_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_UPDATE_PROGRESS_ICON_SVG.preview}
  Assets.ASSETS_ICONS_UPDATE_PROGRESS_ICON_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_IMG_APP_PNG.preview}
  Assets.ASSETS_IMAGES_IMG_APP_PNG,

  /// {@macro assets_generator.ASSETS_IMAGES_IMG_BANNER_PNG.preview}
  Assets.ASSETS_IMAGES_IMG_BANNER_PNG,
  Assets.ASSETS_LOCALES_EN_US_JSON,
  Assets.ASSETS_LOCALES_VI_VN_JSON,
];
